DROP TABLE TB_EXCHANGEVALUE;

CREATE TABLE TB_EXCHANGEVALUE(
CURRPAIRID NUMBER PRIMARY KEY,
CURRFROM VARCHAR2(3),
CURRTO VARCHAR2(3),
RATE NUMBER(20,12)
);

INSERT INTO TB_EXCHANGEVALUE(CURRPAIRID,CURRFROM,CURRTO,RATE) VALUES(1001,'USD','INR',70.09);
INSERT INTO TB_EXCHANGEVALUE(CURRPAIRID,CURRFROM,CURRTO,RATE) VALUES(1002,'EUR','INR',81.20);
INSERT INTO TB_EXCHANGEVALUE(CURRPAIRID,CURRFROM,CURRTO,RATE) VALUES(1003,'GBP','INR',90.28);
INSERT INTO TB_EXCHANGEVALUE(CURRPAIRID,CURRFROM,CURRTO,RATE) VALUES(1004,'AUD','INR',51.08);
INSERT INTO TB_EXCHANGEVALUE(CURRPAIRID,CURRFROM,CURRTO,RATE) VALUES(1005,'SGD','INR',51.15);